"""Auto-generated

Revision ID: 6a76c5d2785e
Revises: e9e1f482222d
Create Date: 2025-09-17 07:27:14.803505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a76c5d2785e'
down_revision = 'e9e1f482222d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('os_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('browser_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_mobile', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('request_timestamp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_logs', schema=None) as batch_op:
        batch_op.drop_column('request_timestamp')
        batch_op.drop_column('is_mobile')
        batch_op.drop_column('browser_version')
        batch_op.drop_column('browser')
        batch_op.drop_column('os_version')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
