"""Auto-generated

Revision ID: bb1c27a8955b
Revises: 6a76c5d2785e
Create Date: 2025-09-19 21:29:13.307252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1c27a8955b'
down_revision = '6a76c5d2785e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_warnings', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_logs', schema=None) as batch_op:
        batch_op.drop_column('validation_warnings')

    # ### end Alembic commands ###
