"""Auto-generated

Revision ID: e9e1f482222d
Revises: 
Create Date: 2025-09-08 22:05:44.193715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e1f482222d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requester_ip', sa.String(length=45), nullable=True),
    sa.Column('requester_country', sa.String(length=2), nullable=True),
    sa.Column('requester_user_agent', sa.Text(), nullable=True),
    sa.Column('requester_os', sa.String(length=50), nullable=True),
    sa.Column('subject_common_name', sa.String(length=255), nullable=False),
    sa.Column('subject_organization', sa.String(length=255), nullable=True),
    sa.Column('subject_organizational_unit', sa.String(length=255), nullable=True),
    sa.Column('subject_country', sa.String(length=2), nullable=True),
    sa.Column('subject_state', sa.String(length=255), nullable=True),
    sa.Column('subject_locality', sa.String(length=255), nullable=True),
    sa.Column('issuer_common_name', sa.String(length=255), nullable=False),
    sa.Column('issuer_organization', sa.String(length=255), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('public_key_algorithm', sa.String(length=50), nullable=False),
    sa.Column('signature_algorithm', sa.String(length=50), nullable=False),
    sa.Column('key_size', sa.Integer(), nullable=True),
    sa.Column('subject_alt_names', sa.Text(), nullable=True),
    sa.Column('key_usage', sa.Text(), nullable=True),
    sa.Column('extended_key_usage', sa.Text(), nullable=True),
    sa.Column('certificate_type', sa.String(length=50), nullable=False),
    sa.Column('certificate_purpose', sa.String(length=100), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by_service', sa.String(length=50), nullable=False),
    sa.Column('request_source', sa.String(length=100), nullable=True),
    sa.Column('issuing_user_id', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=100), nullable=True),
    sa.Column('revoked_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_logs', schema=None) as batch_op:
        batch_op.create_index('idx_ct_issued_at_type', ['issued_at', 'certificate_type'], unique=False)
        batch_op.create_index('idx_ct_issuing_user_id', ['issuing_user_id'], unique=False)
        batch_op.create_index('idx_ct_revoked_at', ['revoked_at'], unique=False)
        batch_op.create_index('idx_ct_subject_cn_issued', ['subject_common_name', 'issued_at'], unique=False)
        batch_op.create_index('idx_ct_user_revocation', ['issuing_user_id', 'revoked_at'], unique=False)
        batch_op.create_index('idx_ct_validity_period', ['not_before', 'not_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_certificate_type'), ['certificate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_fingerprint_sha256'), ['fingerprint_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_issuing_user_id'), ['issuing_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_log_timestamp'), ['log_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_not_after'), ['not_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_not_before'), ['not_before'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_requester_country'), ['requester_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_requester_ip'), ['requester_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_logs_subject_common_name'), ['subject_common_name'], unique=False)

    op.create_table('crl_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issuer_identifier', sa.String(length=255), nullable=False),
    sa.Column('current_crl_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crl_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crl_counters_issuer_identifier'), ['issuer_identifier'], unique=True)
        batch_op.create_index('ix_issuer_identifier', ['issuer_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crl_counters', schema=None) as batch_op:
        batch_op.drop_index('ix_issuer_identifier')
        batch_op.drop_index(batch_op.f('ix_crl_counters_issuer_identifier'))

    op.drop_table('crl_counters')
    with op.batch_alter_table('certificate_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_logs_subject_common_name'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_serial_number'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_requester_ip'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_requester_country'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_not_before'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_not_after'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_issuing_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_issued_at'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_fingerprint_sha256'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_certificate_type'))
        batch_op.drop_index(batch_op.f('ix_certificate_logs_action_type'))
        batch_op.drop_index('idx_ct_validity_period')
        batch_op.drop_index('idx_ct_user_revocation')
        batch_op.drop_index('idx_ct_subject_cn_issued')
        batch_op.drop_index('idx_ct_revoked_at')
        batch_op.drop_index('idx_ct_issuing_user_id')
        batch_op.drop_index('idx_ct_issued_at_type')

    op.drop_table('certificate_logs')
    # ### end Alembic commands ###
